/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author TAMI
 */
public class cari_anggota_pinjam extends javax.swing.JFrame {
    private DefaultTableModel Tampil;
    public static String tnoanggota,tnama,tidbuku,tjudul,tidpinjam;
    public static int c;

    /**
     * Creates new form cari_anggota_pinjam
     */
    public cari_anggota_pinjam() {
        initComponents();
    }
    
    public void tampil_pinjam(){
    Object[] tampilpem = {"Id Pinjam","No. Anggota","Nama","Id Buku","Judul","Tanggal"};
     Tampil= new DefaultTableModel(new Object [][]{}, tampilpem){boolean[] canEdit=new boolean[]{false,false,false,false,false,false};
            @Override
                public boolean isCellEditable(int rowIndex, int columnIndex){return canEdit[columnIndex];
                }
        };
        tbl_anggotapinjam.setModel(Tampil);
    try {Statement stat1 = (Statement) koneksi.ayokonek().createStatement();
        ResultSet rs = stat1.executeQuery("select * from pinjam,buku,anggota where pinjam.no_anggota=anggota.no_anggota and pinjam.id_buku=buku.id_buku and pinjam.status=1");
                    
                    while (rs.next()) {
                        String id_pinjam = rs.getString("pinjam.id_pinjam");
                        String noanggota = rs.getString("pinjam.no_anggota");
                        String nama = rs.getString("anggota.nama");                        
                        String idbuku = rs.getString("pinjam.id_buku");                    
                        String judul = rs.getString("buku.judul");                    
                        String tgl = rs.getString("pinjam.tgl_pinjam");
                        
                        String[] dataField1 = {id_pinjam,noanggota,nama,idbuku,judul,tgl};
                        Tampil.addRow(dataField1);
                    }
    } catch (Exception e) {
         JOptionPane.showMessageDialog(this,"kesalahan:>>"+ e);
    }
    }
    
    public void cari(){
    Object[] tampilpem = {"Id Pinjam","No. Anggota","Nama","Id Buku","Judul","Tanggal"};
     Tampil= new DefaultTableModel(new Object [][]{}, tampilpem){boolean[] canEdit=new boolean[]{false,false,false,false,false,false};
            @Override
                public boolean isCellEditable(int rowIndex, int columnIndex){return canEdit[columnIndex];
                }
        };
        tbl_anggotapinjam.setModel(Tampil);
    try {Statement stat1 = (Statement) koneksi.ayokonek().createStatement();
        ResultSet rs = stat1.executeQuery("select * from pinjam,buku,anggota where pinjam.no_anggota=anggota.no_anggota and pinjam.id_buku=buku.id_buku and pinjam.status=1 and anggota.nama like '%"+txt_cari.getText()+"%'");
                    
                    while (rs.next()) {
                        String id_pinjam = rs.getString("pinjam.id_pinjam");
                        String noanggota = rs.getString("pinjam.no_anggota");
                        String nama = rs.getString("anggota.nama");                        
                        String idbuku = rs.getString("pinjam.id_buku");                    
                        String judul = rs.getString("buku.judul");                    
                        String tgl = rs.getString("pinjam.tgl");
                        
                        String[] dataField1 = {id_pinjam,noanggota,nama,idbuku,judul,tgl};
                        Tampil.addRow(dataField1);
                    }
    } catch (Exception e) {
         JOptionPane.showMessageDialog(this,"kesalahan:>>"+ e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_anggotapinjam = new javax.swing.JTable();
        txt_cari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tbl_anggotapinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_anggotapinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_anggotapinjamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_anggotapinjam);

        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cariKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });

        jLabel1.setText("Nama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        tampil_pinjam();
    }//GEN-LAST:event_formWindowOpened

    private void txt_cariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyPressed
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_txt_cariKeyPressed

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_txt_cariKeyReleased

    private void tbl_anggotapinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_anggotapinjamMouseClicked
        // TODO add your handling code here
        tidpinjam=(String) tbl_anggotapinjam.getValueAt(tbl_anggotapinjam.getSelectedRow(), 0);
        tnoanggota=(String) tbl_anggotapinjam.getValueAt(tbl_anggotapinjam.getSelectedRow(), 1);
        tnama=(String) tbl_anggotapinjam.getValueAt(tbl_anggotapinjam.getSelectedRow(), 2);       
        tidbuku=(String) tbl_anggotapinjam.getValueAt(tbl_anggotapinjam.getSelectedRow(), 3);
        tjudul=(String) tbl_anggotapinjam.getValueAt(tbl_anggotapinjam.getSelectedRow(), 4);
        c=1;
        this.dispose();
    }//GEN-LAST:event_tbl_anggotapinjamMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cari_anggota_pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cari_anggota_pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cari_anggota_pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cari_anggota_pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new cari_anggota_pinjam().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_anggotapinjam;
    private javax.swing.JTextField txt_cari;
    // End of variables declaration//GEN-END:variables
}
